### ISSUE TITLE
Name Change

### ISSUE THREAD

**Issue by escowles** [projecthydra-labs/hydra-groupy#2]
I don't think we should have an official Hydra project with "groupy" in the name.  Although the spelling is different, I don't know of any existing usage of that spelling, so it's effectively the same as "groupie" which is a very sexualized term.  The [Anti-Harrassment Policy](https://wiki.duraspace.org/display/hydra/Anti-Harassment+Policy) says "Sexual or discriminatory language and imagery is not appropriate for any event venue, including talks, or any community channel such as IRC-based chatrooms or mailing lists."

**Comment by jeremyf** [comment]
That's a good perspective. And I agree that the name should change. Right now we are iterating on what this actually is. I happened to have created the gem. My proposal is to rename this to `Hydra::Grouper` and then as we evolve change to reflect.

* `Hydra::Grouper`
* `Hydra::AbilityMapper`

**Comment by escowles** [comment]
👍  I think `Hydra::Grouper` is a good name for the short term, and we'll see if there's a better name that comes up as this matures.

**Comment by jcoyne** [comment]
Grouper has great mascot possiblities: 

<img src="https://i.ytimg.com/vi/SymMh6y3-oo/maxresdefault.jpg">
